### ISSUE TITLE
Replacement for the image of Lena

### ISSUE THREAD

**Issue by xuv** [DmitryUlyanov/deep-image-prior#19]
This is not a technical bug, but an important matter you want to address. 

In the selection of example images, you have included the photo known as Lena (or Lenna).

While I'm guessing you might want to show the behavior of your algorithm on human faces, the choice of the image in this case is quite unfortunate and widely discussed as an **unwanted picture in today's image processing sets**. 

Inspired by other projects, please consider using one of these images instead:
  - [Grace Hopper](https://github.com/ivanov/matplotlib/blob/06010eb80188fe8c89d32a95d1b1b2a04c0ad94a/lib/matplotlib/mpl-data/sample_data/grace_hopper.jpg) from the Matplotlib data set.
- [Col. Eileen M. Collins](https://github.com/scikit-image/scikit-image/blob/master/skimage/data/astronaut.png) from the SciKit data set.
- or any other portrait of a scientist of your own preference

Thank you for your help and addressing this report with the most careful attention.

Have a nice day

**Comment by DmitryUlyanov** [comment]
Hi, we understand that this picture is unwanted. We used Lena image only because it serves an example in ["Shepard networks"]( https://papers.nips.cc/paper/5774-shepard-convolutional-neural-networks) paper, which we compare to. They provide 2 examples of their text inpainting method of which Lena is the most complex and interesting.

So please, understand it from our side: we do not aim to hurt someone's feelings by using inappropriate images, but only produce a scientifically-sound work with a fair comparisons. 

We will do our best to make sure future works use other image than Lena when comparing to our work by providing an another text inpainting example.

**Comment by xuv** [comment]
Hello @DmitryUlyanov.

Thx for taking the time to look at this and for the explanation on why this image landed in your tests. Thanks also for pointing to the "[Shepard networks](https://papers.nips.cc/paper/5774-shepard-convolutional-neural-networks)" paper, it helped me understand better but also realize that you might have a possible solution in it for your comparison. 

I believe that Lenna is here to show the behavior of your approach with image "Inpainting". And for that particular case, the paper you are comparing to proposes 2 examples. One is Lenna, but the other one is a picture of fruits and veggies.

Would you please consider using that other example instead? Would that make your comparison still valid while addressing this sexist problem?

Thanks for your help and time.

**Comment by DmitryUlyanov** [comment]
Replaced.

**Comment by derkinsurprise** [comment]
prognulsya.
